### ISSUE TITLE
Feature 1: User can view a quote  on home page

### ISSUE THREAD

**Issue by michael5522** [michael5522/ajax-project#1]
## 💰 Motivation

The user can view a randomly generated quote upon visit to website.

## 📐 Plan

Start with a static website

## ✅ Task List

- [x] Create HTML skeleton
- [x] Add Header
- [x] Add Body background and image
- [x] Add CSS
- [x] Make the layout looks as intended
- [x] Add a dummy quote
- [x] Fix any issues
