### ISSUE TITLE
Feature 2: User can pull quotes from API

### ISSUE THREAD

**Issue by michael5522** [michael5522/ajax-project#2]
## 💰 Motivation

The quote will change depending on what is pulled from the API

## 📐 Plan

Make sure the API is working correctly and showing a different quote

## ✅ Task List

- [x] Test and use API and connect it to using XMLHttpRequest in main.js
- [x] Take off dummy quote placeholders and make quote appear on homepage using API
- [x] Fix all bugs
