### ISSUE TITLE
Feature 3: User can click a button to be randomly generated a quote

### ISSUE THREAD

**Issue by michael5522** [michael5522/ajax-project#3]
## 💰 Motivation

A button on the webpage that can be clicked for quick access to randomly generate a new quote.

## 📐 Plan

Add a button to be clicked that will generate a new quote

## ✅ Task List

- [x] Add an event listener to the "generate quote" button 
- [x] Generate a quote from 1 of 4 of the API on website randomly
- [x] Add four functions, one new XMLHttpRequest request for each different API
- [x] Change the text content of various phrases on the webpage to reflect that a random quote has been generated
- [x] Make sure the user is receiving a different quote every time on click
- [x] Fix all errors
