### ISSUE TITLE
Feature 4: User can answer specific questions to get access to more customized quotes

### ISSUE THREAD

**Issue by michael5522** [michael5522/ajax-project#4]
## 💰 Motivation

There are four API sources.
one for motivation, 
one for inspiration, 
one for Kayne West, 
one for anime quotes.

The user will be able to answer questions which will lead to grabbing a quote from a specific API depending on what the user answer.

## 📐 Plan

Upon button click, a modal will appear asking user to answer question. If user selects Kayne,  a Kayne quote will be generated.

## ✅ Task List

- [x] Add eventListener to a  yes/no buttons.
- [x] make main two buttons disappear and yes and no buttons appear depending on click. 
- [x] User will be asked up to 4 questions inside which will ultimately generate a different quote depending on what user selected
- [x] Fix any errors
