### ISSUE TITLE
Feature 5: User can change background 

### ISSUE THREAD

**Issue by michael5522** [michael5522/ajax-project#5]
## 💰 Motivation

The user can change the background image.

## 📐 Plan

Make the background blend in 

## ✅ Task List

- [x] Create four buttons and add to header
- [x] Add event listener to buttons
- [x] Clicking on a button will change the background
- [x] Fix all errors.
